---
name: CI

env:
    IMAGE_NAME: trialstracker
    PUBLIC_IMAGE_NAME: ghcr.io/ebmdatalab/trialstracker
    REGISTRY: ghcr.io
    SSH_AUTH_SOCK: /tmp/agent.sock

on:
  pull_request:
  workflow_dispatch:
  push:
      branches: [main]

permissions:
  contents: read
  packages: write


jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0

      - name: Build docker image
        run: make build

      - name: Run tests
        run: make test

      - name: Deploy to dokku
        if: github.ref == 'refs/heads/main'
        run: |
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login $REGISTRY -u ${{ github.actor }} --password-stdin
            docker tag $IMAGE_NAME $PUBLIC_IMAGE_NAME:latest
            docker push $PUBLIC_IMAGE_NAME:latest
            ssh-agent -a $SSH_AUTH_SOCK > /dev/null
            ssh-add - <<< "${{ secrets.DOKKU1_DEPLOY_SSH_KEY }}"
            SHA=$(docker inspect --format='{{index .RepoDigests 0}}' $PUBLIC_IMAGE_NAME:latest)
            ssh -o "UserKnownHostsFile=/dev/null" -o "StrictHostKeyChecking=no" dokku@dokku.ebmdatalab.net git:from-image trials-tracker $SHA
